<a href="https://colab.research.google.com/github/jwalx/Tensorflow/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topics Covered
* Introduction to tensors
* Getting information  from tensors
* Manipulating tensors
* Tensors and Numpy
* Using tf.function(a way to speed up your regular python functions)
* Using GPU with Tensorflow
* Excercises to try 

Introduction to Tensors

In [ ]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions
scalar.ndim

0

In [ ]:
# create a vector
vector =tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix.ndim

2

In [ ]:
3 # create another matrix
another_matrix = tf.constant([[20.,3.],
                              [10.,7.],
                              [3.,20.]],dtype = tf.float16)
another_matrix.ndim

2

In [ ]:
# lets create a tensor
tensor  =tf.constant([[[1,3,5],
                      [4,5,6]],
                      [[6,7,8],
                      [3,4,5]],
                      [[1,2,3],
                       [4,5,6]]])
tensor
tensor.ndim

3

Creating tensors with `tf.Variable`

In [ ]:
changeable_tensor =tf.Variable([[10,7],
                               [7,10]])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign([7,2])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 7,  2],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Creating random tensors
rand_1=tf.random.Generator.from_seed(42)
rand_1=rand_1.normal(shape=(3,2))
rand_2 = tf.random.Generator.from_seed(42)
rand_2 = rand_2.normal(shape=(3,3))
rand_1,rand_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 ]], dtype=float32)>)

# Shuffle the order of elements in tensor

In [ ]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
#shuffle our non_shuffled tensor
  

In [ ]:
#shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled,seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
not_shuffled 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

Random tensors excercise


In [ ]:
rand_3 =tf.random.normal(shape=(2,2))
rand_3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.5706747 , 2.5905995 ],
       [1.109828  , 0.97826046]], dtype=float32)>

In [ ]:
rand_4 = tf.random.Generator.from_seed(42)
rand_4 =rand_4.uniform(shape=(2,3))
rand_4


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794],
       [0.49039817, 0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
#tf.random.set_seed(42)
tf.random.shuffle(rand_4)
tf.random.shuffle(rand_3)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.109828  , 0.97826046],
       [1.5706747 , 2.5905995 ]], dtype=float32)>

In [ ]:
# Create tensors of ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensors of zeroes
tf.zeros([2,4])


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# turning numpy arrays to tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)

#X= tf.constant(some_matrix) 

In [ ]:
a= tf.constant(numpy_A,shape=(2,3,4))
a

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
b=tf.Variable(numpy_A)
b

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

# Getting information from tensors

* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("number of dimension(rank):",rank_4_tensor.ndim)
print("shape of tensor:",rank_4_tensor.shape)
print("Size of the tensor:",tf.size(rank_4_tensor))

Datatype of every element: <dtype: 'float32'>
number of dimension(rank): 4
shape of tensor: (2, 3, 4, 5)
Size of the tensor: tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get each dimension of each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor 
rank_2_tensor=tf.constant([[10,7],
                           [7,10]])

In [ ]:
#get last element of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
#add extra dimension to our rank 2 tensor
rank_3_tensor =rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [ ]:
#alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=1)


<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 7, 10]]], dtype=int32)>

# Tensor Operation

Basic operations
`+`,`-`,`*`,`/`

In [ ]:
#you can add values to a tensor using the addition operator 
tensor =tf.constant([[2,3],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 13],
       [13, 14]], dtype=int32)>

In [ ]:
#we can use tensorflow 

In [ ]:
tf.multiply(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [6, 8]], dtype=int32)>

# In Machine Learning Matrix multiplication is one of the most common tensor operations


In [ ]:
tf.matmul(rand_3,rand_4)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2.447402 , 1.6448655, 2.0582533],
       [1.3113809, 1.0012357, 1.0109487]], dtype=float32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  9],
       [ 9, 16]], dtype=int32)>

In [ ]:
matrix_1=tf.constant([[[1,2,5],
                      [7,2,1],
                      [3,3,3]]])
matrix_2 =tf.constant([[3,5],
                       [6,5],
                       [1,8]])

In [ ]:
new_matrix=tf.matmul(matrix_1,matrix_2)
new_matrix


<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 55],
        [34, 53],
        [30, 54]]], dtype=int32)>

In [ ]:
X=tf.constant([[1,2],
               [3,4],
               [5,6]])
Y=tf.constant([[7,8],
               [9,10],
               [11,12]])

In [ ]:
X=tf.transpose(X)
X

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
Z=tf.matmul(X,Y)
Z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

# Dot product

ALso referred as dot product

* tf.matmul()
* tf.tensordot()

In [ ]:
# Perform the dot product on X And Y (requires X or Y to be transposed)

In [ ]:

X=X*0
X

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
A =tf.constant([[1,2],
                [3,4],
                [5,6]])
A,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(A),Y,axes =1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#perform matrix multiplication between X and Y
tf.matmul(A,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

# Changing the datatype of tensors

In [ ]:
#Create  a new tensor with default datatype(int32)
B= tf.constant([3,4])
B.dtype

tf.int32

In [ ]:
C=tf.constant([1.7,7.4])
C.dtype

tf.float32

In [ ]:
B =tf.cast(B,dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3., 4.], dtype=float16)>

# aggregrating tensors
aggregating tensors = condensing from them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
D=tf.constant([-7,-10])
D
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation:

* get the minimum 
* get the maximum
* mean of a tensor
* sum of a tensor


In [ ]:
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [ ]:
tf.reduce_max(D)


<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [ ]:
tf.reduce_mean(D)


<tf.Tensor: shape=(), dtype=int32, numpy=-8>

In [ ]:
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-17>

In [ ]:
D=tf.cast(D,dtype=tf.float32)
tf.math.reduce_variance(D)


<tf.Tensor: shape=(), dtype=float32, numpy=2.25>

In [ ]:
import tensorflow_probability as tfp
tfp.stats.stddev(D)

<tf.Tensor: shape=(), dtype=float32, numpy=1.5>

#find positional max and min

In [ ]:
tf.random.set_seed(42)
F =tf.random.uniform(shape =[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmin(F)],tf.argmin(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [ ]:
tf.reduce_min(F) == F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.reduce_max(F)==F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# One hot encoding tensors

In [ ]:
#create a list of indices
some_list=[0,1,2,3] #could be red,green,blue, purple

#one hot encoding our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specific custom values for one hot encoding
tf.one_hot(some_list,depth=10,on_value="yo I love Aarya", off_value="I also like Taylor") 

<tf.Tensor: shape=(4, 10), dtype=string, numpy=
array([[b'yo I love Aarya', b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor'],
       [b'I also like Taylor', b'yo I love Aarya', b'I also like Taylor',
        b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor'],
       [b'I also like Taylor', b'I also like Taylor', b'yo I love Aarya',
        b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor'],
       [b'I also like Taylor', b'I also like Taylor',
        b'I also like Taylor', b'yo I love Aarya', b'I also like Taylor',
        b'I also lik

In [ ]:
indices=[2,3,-4,1,-3]
tf.one_hot(indices,depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

# Squaring,Log,Square root

In [ ]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
H =tf.cast(H,dtype=tf.float16)

In [ ]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensorflow interacts beautifully with Numpy Arrays.

In [ ]:
# Create a tensor directly from a Numpy array
J =tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#convert tensor j to a numpy array
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J=tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# the default types of each are sligthly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

# Finding acces to GPU

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Nov 16 07:27:37 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0    28W /  70W |    480MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Excercises

In [ ]:
scalar =tf.constant([2])
scalar.ndim

1

In [ ]:
vector = tf.constant([2,2])
vector.ndim

1

In [ ]:
matrix = tf.constant([[2.,3.],
                      [4.,5.]])
matrix.ndim

2

In [ ]:
vector.shape,matrix.shape,scalar.shape

(TensorShape([2]), TensorShape([2, 2]), TensorShape([1]))

In [ ]:
tf.size(vector),tf.size(matrix),tf.size(scalar)

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
rand_ten = tf.random.uniform(shape=[5,300],minval=0,maxval=1,dtype=tf.float16)
rand_ten

<tf.Tensor: shape=(5, 300), dtype=float16, numpy=
array([[0.2852  , 0.05078 , 0.415   , ..., 0.2129  , 0.2197  , 0.7803  ],
       [0.2461  , 0.3154  , 0.995   , ..., 0.2666  , 0.959   , 0.2256  ],
       [0.02832 , 0.413   , 0.953   , ..., 0.4414  , 0.871   , 0.5674  ],
       [0.552   , 0.66    , 0.2969  , ..., 0.4941  , 0.9697  , 0.006836],
       [0.549   , 0.042   , 0.02441 , ..., 0.0459  , 0.2109  , 0.543   ]],
      dtype=float16)>

In [ ]:
rand_ten2 = tf.random.uniform(shape=[5,300],minval=0,maxval=1,dtype=tf.float16)
rand_ten2

<tf.Tensor: shape=(5, 300), dtype=float16, numpy=
array([[0.9707 , 0.2168 , 0.3008 , ..., 0.1514 , 0.0967 , 0.7617 ],
       [0.0625 , 0.5215 , 0.1924 , ..., 0.8486 , 0.498  , 0.1865 ],
       [0.0674 , 0.3477 , 0.4922 , ..., 0.3682 , 0.2617 , 0.509  ],
       [0.2383 , 0.5596 , 0.00586, ..., 0.6475 , 0.1094 , 0.7617 ],
       [0.0918 , 0.871  , 0.462  , ..., 0.675  , 0.1748 , 0.795  ]],
      dtype=float16)>

In [ ]:
tf.matmul(tf.transpose(rand_ten),rand_ten2)

<tf.Tensor: shape=(300, 300), dtype=float16, numpy=
array([[0.4758, 0.987 , 0.4038, ..., 0.99  , 0.3137, 1.134 ],
       [0.258 , 0.725 , 0.3025, ..., 0.8833, 0.3496, 0.8438],
       [0.602 , 1.128 , 0.7983, ..., 1.467 , 0.822 , 1.232 ],
       ...,
       [0.375 , 0.6553, 0.3567, ..., 0.772 , 0.331 , 0.849 ],
       [0.5825, 1.577 , 0.782 , ..., 1.938 , 0.8696, 1.695 ],
       [0.8613, 0.961 , 0.808 , ..., 0.889 , 0.432 , 1.362 ]],
      dtype=float16)>

In [ ]:
tf.tensordot(rand_ten,tf.transpose(rand_ten2),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[68.9 , 71.1 , 74.  , 71.3 , 76.2 ],
       [74.7 , 76.9 , 78.2 , 76.2 , 79.6 ],
       [75.2 , 73.9 , 72.5 , 77.25, 80.44],
       [70.3 , 73.25, 71.6 , 71.75, 78.2 ],
       [72.1 , 71.2 , 75.  , 73.44, 79.8 ]], dtype=float16)>

In [ ]:
rand_ten3=tf.random.uniform(shape=[224,224,3],minval=0,maxval=1,dtype=tf.float16)
rand_ten3

<tf.Tensor: shape=(224, 224, 3), dtype=float16, numpy=
array([[[0.544   , 0.6943  , 0.4238  ],
        [0.798   , 0.2168  , 0.881   ],
        [0.7715  , 0.79    , 0.8086  ],
        ...,
        [0.459   , 0.4014  , 0.5293  ],
        [0.9854  , 0.743   , 0.373   ],
        [0.752   , 0.632   , 0.9697  ]],

       [[0.2021  , 0.589   , 0.006836],
        [0.99    , 0.4746  , 0.5674  ],
        [0.7324  , 0.829   , 0.6064  ],
        ...,
        [0.583   , 0.5645  , 0.46    ],
        [0.9473  , 0.8984  , 0.8545  ],
        [0.4922  , 0.793   , 0.05078 ]],

       [[0.5938  , 0.08887 , 0.7246  ],
        [0.6133  , 0.03125 , 0.2217  ],
        [0.5645  , 0.55    , 0.833   ],
        ...,
        [0.885   , 0.03516 , 0.877   ],
        [0.02832 , 0.2705  , 0.995   ],
        [0.3652  , 0.4814  , 0.0459  ]],

       ...,

       [[0.1787  , 0.03223 , 0.01953 ],
        [0.962   , 0.2158  , 0.167   ],
        [0.1533  , 0.2363  , 0.576   ],
        ...,
        [0.084   , 0.5986  , 0.677

In [ ]:
tf.reduce_max(rand_ten3),tf.reduce_min(rand_ten3)

(<tf.Tensor: shape=(), dtype=float16, numpy=0.999>,
 <tf.Tensor: shape=(), dtype=float16, numpy=0.0>)

In [ ]:
rand_tan4=tf.random.normal(shape=[1,224,224,3])

In [ ]:
tf.expand_dims(rand_tan4,axis=1)

<tf.Tensor: shape=(1, 1, 224, 224, 3), dtype=float32, numpy=
array([[[[[-0.20061125, -1.2735859 ,  0.48410097],
          [ 1.0793499 , -0.7919145 , -1.1943494 ],
          [ 0.52293056, -0.27564594,  1.2653892 ],
          ...,
          [ 0.03671204,  0.13371521,  0.3438076 ],
          [-0.02921118, -0.3710733 , -0.17355324],
          [ 1.183075  , -0.13284424,  0.05984893]],

         [[-0.22825915, -0.05496023,  1.6530225 ],
          [-0.21462522,  0.9223665 , -0.0250279 ],
          [-1.2404958 , -0.93333966, -0.99086046],
          ...,
          [-1.4904907 ,  0.21620868,  0.3516236 ],
          [-0.45555973,  0.8891502 ,  1.2562852 ],
          [ 0.9425552 , -2.4124134 ,  1.0030372 ]],

         [[ 0.02305125,  0.45591623, -1.6428787 ],
          [-0.34548786,  0.4305284 ,  0.09746896],
          [-0.03441285,  0.6688774 , -1.135134  ],
          ...,
          [ 0.16547878,  0.09162426, -0.63121545],
          [-2.260828  , -0.22484669,  1.4544208 ],
          [-0.1619715 ,

In [ ]:
rand_ten5=tf.random.normal([10])
rand_ten5

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.5440758 ,  1.3154335 ,  0.7808076 ,  1.0706283 , -0.9656791 ,
        0.25132164, -1.8545105 ,  1.4713811 , -0.7334912 , -0.344911  ],
      dtype=float32)>

In [ ]:
rand_ten5[tf.argmax(rand_ten5)],tf.argmax(rand_ten5)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.4713811>,
 <tf.Tensor: shape=(), dtype=int64, numpy=7>)

In [ ]:
rand_ten5[tf.argmin(rand_ten5)],tf.argmin(rand_ten5)

(<tf.Tensor: shape=(), dtype=float32, numpy=-1.8545105>,
 <tf.Tensor: shape=(), dtype=int64, numpy=6>)

In [ ]:
tf.one_hot(tf.cast(rand_ten5,dtype=tf.int32),depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
grocery=tf.constant([23,46.6,29,100,34,57.5])
grocery
tf.reduce_sum(grocery)*12

<tf.Tensor: shape=(), dtype=float32, numpy=3481.2002>